# _config.yml

# Site settings
title: "Research Page"
description: " modern look."
url: "https://labrat-0.github.io"  # Replace with your actual GitHub username

# Theme and layout settings
theme: jekyll-theme-cayman  # More modern than the default

# Custom styling
sass:
  style: compressed  # Minifies CSS for faster loading

# Plugins (optional)
plugins:
  - jekyll-feed  # Adds an RSS feed
  - jekyll-seo-tag  # Improves SEO with meta tags

# Navigation (if using a theme with a navbar)
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Projects"
    url: "/projects"

# Social links
social_links:
  github: "https://labrat-0.github.io"
"

# Excluded files
exclude:
  - "README.md"
  - "LICENSE"

# Markdown settings
markdown: kramdown
highlighter: rouge  # Syntax highlighting for code blocks
